# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
  labels:
    app: frontend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-server
  template:
    metadata:
      labels:
        app: frontend-server
    spec:
      containers:
        - name: frontend
          image: shinyubin/image-converter-fe:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fe-secret
                  key: VITE_GOOGLE_CLIENT_ID
            - name: VITE_API_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: fe-secret
                  key: VITE_API_SERVER_URL
            - name: VITE_AUTHENTICATION_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: fe-secret
                  key: VITE_AUTHENTICATION_SERVER_URL
