# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shinyubin/image-converter-fe:0.1.0
          ports:
            - containerPort: 80
          env:
            - name: VITE_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fe-secret
                  key: VITE_GOOGLE_CLIENT_ID

            - name: VITE_API_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: fe-secret
                  key: VITE_API_SERVER_URL

            - name: VITE_AUTHENTICATION_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: fe-secret
                  key: VITE_AUTHENTICATION_SERVER_URL

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
