apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-converter-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yubin-image-converter/k8s.git
    targetRevision: main
    path: clusters/image-converter
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
