# image-converter-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-converter
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      frontend=shinyubin/image-converter-fe
      api=shinyubin/image-converter-api
      auth=shinyubin/image-converter-auth
    argocd-image-updater.argoproj.io/write-back-method: git:secret
  labels:
    app.kubernetes.io/managed-by: argocd-image-updater
spec:
  project: default
  source:
    repoURL: https://github.com/yubin-image-converter/k8s
    targetRevision: HEAD
    path: clusters/image-converter
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
