apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  namespace: image-converter
spec:
  containers:
    - name: test
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "[✅ NFS Test] Writing to /mnt/uploads/hello.txt...";
          touch /mnt/uploads/hello.txt;
          echo "Hello from NFS!" > /mnt/uploads/hello.txt;
          ls -la /mnt/uploads;
          sleep 3600
      volumeMounts:
        - name: nfs-vol
          mountPath: /mnt/uploads
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: uploads-pvc
  restartPolicy: Never
