apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/yubin-image-converter/k8s
      usernameSecret:
        name: argocd-image-updater-secret
        key: username
      passwordSecret:
        name: argocd-image-updater-secret
        key: password
