apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Argo CD 내부 리소스와 매칭할 때 사용할 label key
  application.instanceLabelKey: argocd.argoproj.io/instance

  # admin 계정 활성화
  admin.enabled: "true"

  # HTTPS로 외부 Git repo 접근 시 필요한 인증정보
  repositories: |
    - url: https://github.com/yubin-image-converter/k8s
      usernameSecret:
        name: argocd-image-updater-secret
        key: username
      passwordSecret:
        name: argocd-image-updater-secret
        key: password

  # 선택: UI에서 보고 싶은 프로젝트 필터
  # resource.exclusions: |
  #   - apiGroups:
  #       - networking.k8s.io
  #     kinds:
  #       - Ingress
  #     clusters:
  #       - "*"

  # OIDC (SSO)를 설정하지 않으면 아래 필드는 생략 가능하지만, 기본값을 넣는게 좋음
  oidc.config: |
    name: ArgoCD
    issuer: https://accounts.google.com
    clientID: example
    clientSecret: example
    requestedScopes: ["openid", "profile", "email"]
