apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: DockerHub
        prefix: docker.io
        api_url: https://registry-1.docker.io
        credentials: secret:argocd-image-updater-secret
        default: true
  git.commit-message-template: |
    chore: Update image to {{ .NewImage }}
  git.user: YubinShin
  git.email: shin.yubin18@gmail.com
  git.writeBranch: main
  log.level: debug
