apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  template:
    spec:
      containers:
        - name: rabbitmq
          envFrom:
            - secretRef:
                name: rabbitmq-secret-dev
