---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: image-converter
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCanWXun7aCR7jBg86Msokvim59RjeXD8ob/5slW92lQ8PROzzQvfkCqlx/ksUkhIPsvf5VqBLf8Gv6BTPO4WV33+3NyhMPYX8n+/EW5gXpHIRRQPl/xEOeAvqw6Y8WnNmP35m+vFdSJVjCyIZVhLuuay2t0OenKqPURpT4SkSPzWZedsFwmiLycoM0LE25OuIFc0Pnl9E+iskaeE5keJxBcyZacG/EmPACoWQPI3trHnhC3Z13HeaOXw8J42L4Tlu/6goaLv0mVyJKXky0K+tDsM3Fjlw+ArOluwoUS12J+Ou/DwtlQMZUMYISjpvvxRE9NmGeeFHwMgLzHIg0jracYWHii04bF9RYha417uobCZQTbl7zYGPtXGalHxEIQq1U/6rIEZG++RIQkYzlbSgRKiM5w79WGnhfolIlI9T3d+zfacNRqo0UXG9fKTU5SaJJeZApyR19Q+OKfutLuczGvwe7ECWPMBnEJAEp7f2t3YiKZWzt+shB9nC6eiszViBZyWqMVGYNdxsSTGwP9g7kSvuwLWSGSjFtaXanxYxXLha0Y0yAqdOoLsPb6O+vbdHTxrVtjK3sYFhP2IMQzsx23axpiR7uDRKVMjA3Q7aC9a6XiQxQAzDTxozUspMXhA0EOgkgO+aXCUIestZP2ndaFCAQLoQv7hTq+36PF2LAQiM7HOnNYEu3LC6DkAghvmKve9xtcw==
    RABBITMQ_DEFAULT_USER: AgBujezyAoNFMK9YAhvPFajAmbnByce/uoErr4ngzUwnst4N8q35m9b68zrF1a5/YtHWdoCDa/S84nlkEbg2UnPklNAap/FvwVaJlMNo2RxkiMHTqALKDCsqa1lJUxss8tsZJ0m3kA/SUZOq28EYWxrsT7UtOxWxdQjqv/4Ql60TKZqNQii+/hI8uUJ2718JNh0+6OoVzfqqJFf/H467r2aLgigTCdOGn7JqgcsLYFHaEtrFSXUhP9VbMPSvi20KSrcHREHp2QSN1ZxGWIpfLu8ms2Db3HWHj5JCPHyzX/yodR0IcUVADHa9ZVk7KwY16nhtDghBiGzYW1cW32ABhb+riEouTBxmuB9wsEprQccAdY48WAIQyX3Cw5ubvK8AeO1Qz4CKp0Yjehr43Iz5MDBXdGIqgWnKI4PKnJeF24gVNvPjEFR7y3E6l5Stnk+TVxfExzk/a7/e28sL4+pgyigd52wI9U3lmp4ONYSP6pj7ia46E7o48fcE3M/rLk4OzyxrW1peSS6wYM6zgWVb5bBkrI3nBv2VXMPLLwhEb2mGMy11nMwePAt1uczusy8IXJsx91J6GIlE+T3prpDYQ9zKo4TbJUeC0Lwv/LZKP/ejk5sfn8G0AEldAy5L4rqcFpXHvmRTW/oo76y9WzMF2W2xzlsbmhxDUDrCpMB+R8uC1DK9VMXAKNnw6XfrNGi3/+bYvUbH9g==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: image-converter
    type: Opaque
