---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: image-converter
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgAYzSXIkfa/WXH7m2RFcJcKKSWu2PPXU1gekIVC1o3u76W+hSrlTd9MXnH4rl1f8Joq2CUJn84lbvvNu0ncmJyAK3uCRC+xuHevS2TNwYMhbvfeIqkr6lC3klAR2XEFIiboLH6MQh5XES+Yov0lsLc/JtO2O/Q/jrrhw//q9Q/RFotO55L7pqMV5ESYqHkHtS2gtaN1TFCPmvgB9X6bvxFsbgqi4so8lDK6JqBTk/ox4Q8ouTHYm1rUnPWxPbcpApDfNswMB0nPndLCEael4ZQii3OE54LTdjK8v0h05mO0BdsmvpFF2aMGhedyqNbbMZhkob+GLXYlHdSt2LXyEjV+7au1WeXBF57uQYiytjsbU8CmpL9kc/rbrXZHRa9S7k8LgQyJB29GXK6hCiN11MQLKZ0DE9+zIt0UTZyltQeWX+t+mAgTTsJF7xx3irYIUoq69oWJB8zb0tgWRfKs8He652c0Pl1yduXStfYutP6KP91LfmLbrAFI+vgNZ3T6UEkE+HRKXZqPfAP6H153xbSumjkTXt6ROEOEs3QW7CUSCCSKfwmq+Fn8OKq3A/41gJTQNHX/LMLIN2tbRu+s/qHKnmyJPprW2n2JhSI8qx63i70Q1Aj8XrYFr342uvdfpnjeqrysimHUQaww32I0MlPLNT+Ndd1WU97x9IatwBLZARoSAuCfZAPIT0FSLT2XNJ1HqnTEMg==
    RABBITMQ_DEFAULT_USER: AgCB1ytAPLuzp8p014GGFkkb4AgULkPdLsCt1vt8kFmF7R0mFqNFYLxTp4X03g5a+lsJHvyEXgFr3XKm9qMPZPWyU+l19gtvJ1GZoeMLexNe/GOEg0rt6C/ZDYtfMwMaSaE7U7QeQFsjoZq2BulHzQqgkvspOvJ/jo1li2tRuGeJwKABTv1pe/hLxBGrQ4f2Iy1rY6oDQ9Wu8KdoSkFMpyrsAywb1GCHDtI7LVRvttVbCJlFvqYLNftbJhMSxI2QAmFic46MrpVwMMx+KTK3OfqTVT4W5Lo06ZM40pkNIhJouC7xCGM4AUW2PAGYQhkkEuj+5Yb5x4bBIYRosjwKVKETWQRtb1pv/VydgauY+r6Lduie5qc5QSXuKtuPHVd6ljra+5J3D2MBxr6I9c6ftx/2r6WkTTCpAN+1bVIqnBJ+4sKnK7PoGJ1NIFUjVaRTJliICeCqH45KW9HABuVXykRh9ZF/gfq/LcyD30uIZnZOFoQJSlwXpDcFn3qqKT1j7j/AVdJ4M12dTxh8MlqbPj2N0P36jNqNgJ3UcyZPIFQYs3w/grg6EafYJ1wc032fubqjjv1GG5NdjKYf9YD1soowOGo0IrWOEyFf1caD79V4umhrtuPcqF1cRtSR84j1OqNyjGBKAn6IeF84u/LT1YuVkusFvK0bglS9rhnwH432pUVtTNIdgsdqMZ1YlBRILVwVBTT2LQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: image-converter
    type: Opaque
