---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: overlays-secret-dev
  namespace: image-converter
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgBJv6zbRp7PAT1gmeO25ITCdOF+UpFP0KA8yqhG+G7NeDEoWz41QFp32X8RvqcdiFmZyEp/nunS6nF7IIDrofV5oHS+7o4cCAkl3h/CmkOxrrwCNIiJjkBlDt0nCguV6I3b4Vcs1YTN1fC24xfS4/Gjp+RAbqdmRn510FCfqh0ITxnKlSj1tDTwXKa6OVpn5Ejz+TKASHvBW0qM5ib0N9NuhsUEAxeAsorpAh7lyFLnSQWLEkqM9D/XwQYG1GSWabTKwLWd/AdjUccSekxrru/LKcpfu0PZhWZmo/rUXwsh0IG9TU7h962vWBsbGMQmlwQKex2c3Ij2b3HK8sRYihIH2ofcBTLgRt7pWSl+VZdwRUNcN+N7ge+SRaf4BVi4X4KBPXkIjYXareUteIuocigDyCyVaaw1ImB3I1fJZM4uBqhctg6mmZjvhhi8sJ3fot9Ur2feGs75FGtvX1crET9ZUyumNCrMsWFNeotEKdbT1yPWu9vXnoRcDYdWWbgwFxtsQ9/M+t8obEM04aAlNo4HzenMkPGiJDepIvnOluvGFoSjTaBOOEqF84UlfkcCjrF+rm42TzzGhJ6CzfrHGc+AFlrox/cQsRrbkmvzmyyNLzMh4vrhy2yLConFDgTBCM/1YolKF3IuLERTtUz9RfNmJHD5vADXnfdBUIVugLQQMqIits6ARjye17hxr6AA/9KEiJ7MWg==
    RABBITMQ_DEFAULT_USER: AgCEcp9BaeeC0lCjKmUnfIDNEfS6bj3CiMS8JjpHhGlIVelXvPbDf5Y7SDEFhfSSgkmpdoWbZD6RaHdLLj19BmymWDp3bXgtvJ3IGEMpnUBpfKl+A/Ni1ZxOa97aeoG+vr/hKFMkDOH+u7oYk4+wGjvM8TBKLAViHq+EOGVolCd+6WUSTmGmfuYXfdsNdnAvGKJ3WfruzT7NKBVL4KktC6VpMWu/a///ru68JdwccNx/GmrcSbLQ5t82EtucB1FT73a+TtI06+j/FH0X99MiwOK3NQ1SRnQjFvcuw5KRJF+srDt8KU3wVI0FiHGIh2XNBq1sq5cZEptNxh7KmCIfkyKW/dfNkIMmXZQoB3qVgG2NZf3qZYJBL1F+M17oFgodqME4jjb2u2RpRUSsu9cLulxWY2aYRfDk3npmFLuKTTjhQga4FXlFpQJJo2elDMEssEk5jcvHEbkGb619yhdDrKlmcd7u3TH+Ko4RKoo6GNLcRcIEsbgxIV2+eAbgJs82H+24RBDsMK5DFkTRTCPbUlLCh7txD00mmlggbpAI86tWGJ7BQNs2t3uOHqg+0TFByLLmczZqNiZggosv58GzWf+tSyMkDFkI2lB9Tgimem30ehGRRAFmSi89qYorzfLeqtlbqkV/ZmmaoIDG/F9J4nYkSXT9P3dmBLZXj7toQTR/OS9Sy2egZQqROdhJqQObdFK2bcI3iw==
  template:
    metadata:
      creationTimestamp: null
      name: overlays-secret-dev
      namespace: image-converter
    type: Opaque
