apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-env.yaml

images:
  - name: shinyubin/image-converter-api
    newTag: latest # 원하는 태그

namespace: image-converter
