# apps/api/overlays/dev/patch-env.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  template:
    spec:
      containers:
        - name: api-server
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
