apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  SPRING_APPLICATION_NAME: "image-converter-api"
  STATIC_LOCATIONS: "file:/uploads/"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_DEFAULT_SCHEMA: "public"
  SPRING_JPA_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_TIME_ZONE: "UTC"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_DATA_REDIS_HOST: "10.178.0.3"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRINGDOC_API_DOCS_PATH: "/v3/api-docs"
  SPRINGDOC_SWAGGER_UI_URL: "/v3/api-docs"
  SPRINGDOC_SWAGGER_UI_CONFIG_URL: "/v3/api-docs/swagger-config"
  SERVER_ADDRESS: "0.0.0.0"
  SERVER_PORT: "8080"
  JWT_EXPIRATION_MS: "604800000"
  RABBITMQ_EXCHANGE: "image.convert.exchange"
  RABBITMQ_QUEUE: "image.convert.queue"
  RABBITMQ_ROUTING_KEY: "image.convert.routingKey"
  RABBITMQ_RESULT_QUEUE: "image.convert.result.queue"
  NFS_ROOT: "/uploads"
  HOST_URL: "https://api.image-converter.yubinshin.com"
  LOG_LEVEL_HIBERNATE_SQL: "debug"
  LOG_LEVEL_HIBERNATE_BINDER: "trace"
  LOG_LEVEL_ROOT: "debug"
  LOG_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "debug"
  LOG_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "debug"
