apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: shinyubin/image-converter-worker:18
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: worker-config
            - secretRef:
                name: worker-secret
          volumeMounts:
            - name: uploads
              mountPath: /uploads
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
