apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  mountOptions:
    - vers=3
    - proto=tcp
  nfs:
    server: 10.178.0.2 # ← 내부 IP 로 변경
    path: /mnt/nfs/uploads
  persistentVolumeReclaimPolicy: Retain
