apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: image-converter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeName: uploads-pv # <-- 이걸로 지정해줘야 함!
  storageClassName: "" # <-- 없거나 빈 문자열이어야 함!
