apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  template:
    spec:
      containers:
        - name: auth-server
          envFrom:
            - secretRef:
                name: auth-secret-dev
