apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  namespace: image-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: shinyubin/image-converter-websocket:5
          ports:
            - containerPort: 4000
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: websocket-config
            - secretRef:
                name: websocket-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
