spec:
  containers:
    - name: websocket
      image: shinyubin/image-converter-websocket:latest
      ports:
        - containerPort: 4000
        - containerPort: 4001
      envFrom:
        - configMapRef:
            name: websocket-config
        - secretRef:
            name: websocket-secret
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
