apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app: websocket
spec:
  type: ClusterIP
  selector:
    app: websocket
  ports:
    - name: client
      port: 4000
      targetPort: 4000
    - name: worker
      port: 4001
      targetPort: 4001
