apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
spec:
  template:
    spec:
      containers:
        - name: frontend
          envFrom:
            - secretRef:
                name: fe-secret-dev
