apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev
namespace: websocket

resources:
  - ../../base
  - sealed-secret.yaml

generatorOptions:
  disableNameSuffixHash: true
