apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  namespace: image-converter
spec:
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          envFrom:
            - secretRef:
                name: websocket-secret-dev
