---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: websocket-secret
  namespace: image-converter
spec:
  encryptedData:
    REDIS_URL: AgB/0UeyYHsHfox1GYW3Gov25x6YUuPo3K652t/FHPTyQmfwK59QeWfsDHPeOsunAVQG9zmD8CX4bwXXjpTpUfmQjKjOJlWEI7psB1gZJTZjAnILsFIFKoAv+bpU3H0M8EOfYy1QUPSgLc7cKS9Kx7IB+gjBSBgiYdazxjsLZAAOBdCMx06VG6OXaxz6FwdukyQiDjmdvsUclQcjk8L7mezTdGeT3iA+2yyvNuHx9M/8cj9tijYHMD0fHjSUR3md4HtmleZ9kE2wu9borPwOPG7mZpOc3AxdgaROT6HlvoccvoqZcWQaDm2TRiAPe5RuqeIgkXCAWlmt6hAGRk2rHOcypCcwELt0EQCpaaxA6+xtZ8tiDqpNG1HEmGaAIIRwKLXzzKWKEH5BCmV3VtNULbqmuR/cf5PBI1e0WD2y94FdPFDxebzGR4tRrCWh7kXWvAoGBKkblcmdTfjCUZzySZLE4Nz6FD4ICsLTLQQpUusKaBSi4VGH1aQsYiErzjzcmfeDmCFSnn9eNLwMN5o/xTMJgFRq1eeUB62/paMIfYcfv09hYI8VgtLdALIbcmPRARVfzgvl5fHBUAvxOLXCgQuXBd9zX1Q+S2pZ621lWNIbwl/2kvVUHkQ0qqA3+cUyAnq/FIdHHAdfgoFCiCydN1LJzR1eB6KgPhckMkU7701Fs71Igk5pwHiOhnHm+tVpuehI/t44x0UI2JaKCPS9ncFkuyZtnsjlMwqbAYXSNYsuDZUo1lWkK3Q=
  template:
    metadata:
      creationTimestamp: null
      name: websocket-secret
      namespace: image-converter
    type: Opaque
