---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: websocket-secret
  namespace: image-converter
spec:
  encryptedData:
    REDIS_URL: AgBLu9sZ9J4kUcERxWid+df2UBMsSZbjJjZMtiVUm28xwLtplnRSkLplZwoPHPn7Yzqd5J7vHO8FoIZOquYebx/Cges8wvbN04ZG2j8HMb5sUX6iTOy22m5s2i6yUEZIsOZ9mTLQDSAmB0SeMcJ7ycJ5q6dBFkZ3L8vOX7Z2F+T/Qie6PlFk3hgNDZwq2q7tPqm6x4FL4VaSnBnbt4vrP6U0ncLwIO2itNc6MJjrkHOvksy200ktuqXXYcULmldkhXapA9orFBjYVGqogof9iFeD2zsefKL/Sw+9ZKlX+szB1DxI6vLg0QJIOKEft0Ml665cqaNMg1X+86Rfd/NwxtbX/0nSbif80DWpJQ0poBlcamiY7H1WXkxwi+27WNSCoU9xACcb38VvfC7hehR67CDtJOM6PB/K9CFIxcaf79NgeH1Q+jmNY2r28A8341WedPO6u2FszDdMIp2hWlOn/AcuXL1ZXXRBNApMmDaSN0D5sM7D/gm/Ryn9ztvboHG4+22bJdQq1ojlWB8u26jsTSHMJBiB3ziXiJv8bo4yZiSSPsZmfSKOcDn0pkDUbKzV5QQExmeOQx+6UHwDEJBXBeSbKvGQc3NEA4Wh3i7SAUR22ig+3ua6edJQgR7gZq61qADQIz1CXOnxQ7vXqsTZTSuwutdrsUvRhwqtjQ/XkqxlTk2PyU0zwExUE6BkQhOBVKkdhNkbakr3Ps4GFqgrlvz+b8Ho9TcdcmAVuzW0m00ci8ndu+MyMJI=
  template:
    metadata:
      creationTimestamp: null
      name: websocket-secret
      namespace: image-converter
    type: Opaque
