---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: overlays-secret-dev
  namespace: image-converter
spec:
  encryptedData:
    REDIS_URL: AgA+4+4f5xy+Q+s8DVjK/43exZZI3949RsORaTGhf/u6rDkQf/uhQtyNmdnXz39GE74/RUMAyCT10fQRZ1GwuOvvCB0WSFWATAg25fe2zziIJ0e52rZA8D5y7iWCsm7uvhFL0d1aRG3UuO/+8gfj1yduSJz0WEkXkR9B4d01yQyjHnXasOVstxKQG7+ObwQeSf9YBCopjff46UFfqeu3mbafAU9IBqmikump2KrvP50nw/VVPhPRk0sREyG+gHBxZ+aFW5uwe/+uXGNjrGK8xg9yyt6KvDepWmJrKx5QUJghTADxoX1PLB4s3/SkPy7GzKgswiYgZ63TRIuqk05AMRGshSntqtYvJiwbl71GScKZ0SuB3Oa2ZxS3tFYdMiDHmHu1PXOCY+aQOxcFyxpWpP9gf4NlFI6xSpxyXvthbQgXcTMyA0GGygszr1Be5mvrbwVSqWkTwGauZB1guhE5dTU3iuhsLhWH1VjrjplEFTF4Jw44ZwRUZ/tA/WzLWKXakb6ufMs5tEokMh2+h1sKRuckgBV96K7C4X8HGCuOWodcJV4KXfDgk8hSqXETQNoH6GUeSD+Wy/dGmwuDPSM+2QVxI66OBUKoGJfMJTrQblvF5tElab5B+a6neJkBymTgxDrBj6/A8gPzXVgj1e5J4xzfhxYjO1yekLe/MPOOSEaJg0WFNK5lOuSCF8WNcvbmoOJoMDcDRSdj+TFRd5bNmqse7b30WldJJ4ojr7OfYruKdLlwv36duQY=
  template:
    metadata:
      creationTimestamp: null
      name: overlays-secret-dev
      namespace: image-converter
    type: Opaque
