apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infrastructures/base
  - ../../../infrastructures/nfs
  - ../../../infrastructures/cert-manager
  - ../../../infrastructures/ingress
  - ../../../infrastructures/argocd
