---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: worker-secret
  namespace: image-converter
spec:
  encryptedData:
    AMQP_URL: AgAeDFF84VfMFBlNXxOcOEG1r+5Oy+jCloyrD7tE3ZTYH3JC3WokcQF2OlWTOYBg0piiPy+8xZyZJnPOCSQAQcQ/sWP5n1g5HlMiCMluiLHsPW8Ii6xOuUsD7bLmsZwZ8GkYx0x9zPaNkiD2H5zC+c+uP6IHEvbPxXoCkC5ev5+cHOVpKe7oSFSGpvtRHLwSvjW4ulSieYr12f7IjzG6ZSrGjnTTIEBiRneTm5rksRpkn9L4LS04ZVzPtCosU2izygQdzuFTEFBrbCV6ZbWY3usRjYxq3yC3IaLo1DyQgI3dU1ZRNMFKe7zYpcwXj9FJSxDSibrDQdkGzBnx+oUjCo7RDIpwV0zfJ0LaIDs3xbPlYFQRRzXen5Jlw5qEowJWjnGMgZeUFoHtZ0jEi5lAeEohb8H5Wt/rHWvphKw1YU9SWZx0CDi56WKtfv6s8eYOgRsdriBDugjJ1Kibj8wZOAVg9po+/GtYbQvjjABJR4rVt6rDKbnYLsdGXlXfPsp/wslkUrR/zjvSMpRq8THydIorlct5UUJm3kbw8AqS96xKaPJv87F78pf1P6hc+8+sqtv3v6wrIx09mE/l0JXmGZLmcBUJCmBN4ACprILjksfgcAY4iEAO4domXlZw7hTgmqSpWLoT87u9CMsskCYjKry69UveLVosBHA72D74bDUj87Fs1GjIFjfgGpMcalUMGu7iKS0LrYz+OLN2va/0kWOKFFiql0iuDzDzF5MpKNtEsA==
    REDIS_PASSWORD: AgBKOedPvBmZRQme+aHwnp0pYdn2ughW53tu/qZWE924RcfUXWH7198csE9GH7UDzvOlCW0mqJ5yz7kaJAx8aJ6Vt72SNdceMpvxypwCIXPqY9zBs1UKGxQ/20m2Rg2HyMZbRQ2BQJa7fu/3YuTHDfxq1K1NUijtglaOnpMHlxFM427g7K+JBzUt3ERNo8ueo3mpyZFN4hjQcd0CzvIZiaL5ehR3ByLZXdUZJJI6sq//Kp7q6zL6rEDkwB9MUJSH1UN+Rvh23vFNxFVhAeTVo15fdeRiL7y16KTokG4VPoEG5O+UPV2LxT2USiN8gvxnup4zS74wDKTDUtbKICjjnbURecfIq5/Kq6AHK6HhBCbnyJZPMfs9BvbpykVnisTofX6ZA8U3mL+ZsreEa8sRin0/G/cPwXnmNSbQ8TZ4P0Nj5tz0RluFVqFxJFTHCaysc11RhGApR7pWJzUXcweOALuF86ScLCCwIS7yk3J5kmLn8Z88MJ8Uum5zqtsutwREI79ogamUgVmgJCBp1lOQP8bFtYBSidoXbQrU5+tjod3s9rY0ItGQRQLsmcRe9yCAh9/kgGf6vP4ZyfG/sOsz2TA3UR1agmmQSw72EFpi6D/56TjFVmgV2BVqN8G2V9b7d8crOJ6DyLPIhUzOgeOvgS2wOMGbtSbNSptwcSees0B8QCDP2/ewbFvB6Y/oFxzUygYnsUJ5Jw==
  template:
    metadata:
      creationTimestamp: null
      name: worker-secret
      namespace: image-converter
    type: Opaque
