---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: worker-secret
  namespace: image-converter
spec:
  encryptedData:
    AMQP_URL: AgBLVz6VS00xfRPLGbMA4fWOHQsQFcHSdJNaYnuSvk/CP2yGOvcsS04bjGFnMqSABeqs0Dbnvjtmm1LYc5Kz1qJcaSGaBO6X+UzGEyT8k6aDKPXB1RI0GtF/1/zjTBldbUCTobrBiqC1uecokMiYCW+lVSKfUK+LK2ZZXKhoKt6HSXwrt4FthdGVU+xPiSXG4HSpS3Rvde+OM7AQwnB+tmMy0snjkDIqhdhJ0qItVc0nBaCZZuCQKKugKJcvTDHn7rJbYHtKs2UBzQfGwWH6moUYRvUmMN8SHBV9E3BbWMTZghIAFPCNgh+ZuUnhD/IsjCvHMvITgqgNlZOlaWML1fuE+C4chC+8pl92w4p7fPLYzMCeM3yINTtia7dm0CTrIkhnC6emceTxlCImVxmL11ImOK3aE9hN+KipCrVoDXmlTrIlKiImWiqNRjkEAVnTnNzRg4gYDhr3GqNsx30olnB3X7ke5HyeixRcUAMKVgdkK6JX18FCJSMW3h9SG/cnTRGC6HAYsrUIVsQBW2n9MQyPQKj/SPNRneF9NeoiSnI1esY2eXcVufL5AnSdxt/cp4aKPo98WJPQphSw4dyItvcZMCgzyT6OfkWPBg+8AKKPsg0+o1flY4K3EFAi4NmiX5wQd1JByDRhHvNavUv9uZmaue0RWCfpj/NQ1cja2JNkfA1TsdohHSjmBn9ZKowd91Bo1dsAIGhAbgOyZKAX8gO8E5RBqbJ30S7Mo0bbr8sDFg==
    REDIS_PASSWORD: AgCbd2wJnWG6yGgnQ82jqmKTQV/hCXzMARWezNm5oNLR5pMUIoAmqe49UPS//80CowUXH6P1H206jXnZ3jyXgvhc7Er1geXHFBj99VyfG8umWDVfky8szkjMo+YFilqZ24ToAcQLTwrJGCX6FwFZ0tVW53jXl9yMP7YmnNUdHjM7z14+SSBpXyuN7Hu33YmdLUBKdwZwZWHgO44iA88+zGFKxbYJln7aR04fWKC1+ec6XXNJD/Qa2EPEyaHQefUdpVA7aJTmo+lGQ1FV6tXLEJ+8zrzDTVhiMtcnbdvAFjO3PdsqgYL/6X+AaJUduDaUCMo5XqrvWDG4ScZEuosXwnfg1DSmJgN/AUiu1T6/ekzzKS7ydxH7Lr16snLkxmMpmOiuHgKUaG8ms3yARFVgJWGGS2qU2v9ayfExhfegfUODUXVRHg8D7baURpLoxHIovkNkg60POHyQdDQPkdqQN08cJr4I5Eq7hNfmOuX1FqaXYO5cq6YJs1jqFI777Hyh7O7oqovcJShIMbDngPWJlV1klSK03m5cUDP6CrP8kMeyltYlcBZ6k087F+FXYQ4ab9WmDfz82z1KWdr7/5UBf7YgIGFtApX0Q02tjxLLwAfoXIpjvFSlWdSFnpM64jWXauEl2Al7wnlJGnN8UllkvHr7bMj4RnPawP/s0Dcu8pIt4AlTvf9n0pMtEK0h8nv0WpiVrKmZjQ==
  template:
    metadata:
      creationTimestamp: null
      name: worker-secret
      namespace: image-converter
    type: Opaque
