---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: worker-secret
  namespace: default
spec:
  encryptedData:
    AMQP_URL: AgCVQGNdlQXYTYWOtofihm8LwBUbtDC4LfnoPUqD6FR9dB6Gl3wMEIcWKtusyeeNrQz0JVxQD7GTZZCmmElrD/+jM3EhrMs96qKMJ/WiueT8+Fhc7YgsLlUA2LN5NhgSfj7AfUkuUBIL1Zdufw1lohq/WoKhEgx3tjGCvFJI7ke/aJ+hLYZ41t2zW+wHojP6fbEajl/hW1tNt7e3v0sLC/ATT9Eig61YdwEqY2XkqhY0ormgt+Nj5QJ6e/4B1lWe5RcbVe9fVLP1lUuSp32+fm7GiiJmckt85wIlEhcKUGPUUnj8sXHUc/nL9BACEgsHmnRAzU1KYhsmaBAUZ0k92MWd/SNQ1MASgHlsfpDPPQeuAESti4PKwj2TpRm8KH/CRfwyNfNrTpjWjSGD1i6Hg9CUPa/z+269mQKNBN7O5vPVJyNv1KQDPcZ5h8rx7OqKAwrziF1Cb0hcA/0nRrioGdVKxSgqdPepMgqpsaAfU0YI/ipV4EibkHiA6dKRJc7gtYV8YynhvOrjFKDGkLOF3pOstzzZ1rsF8t+JCEAmOvTZvGW/V5Cw6kk4ml/zf8QaC+CtD7cxatdLF+q7oJoNe6K2g8K9tY7VaXbRgN9K8Ap8vCGbS1Ua+rj/0ukRT1NW+NoWtgMTQeVtEoW5v7DtEPenfmqRkqPfbbeuuwVnCtcx9yHsS9rTbAy4gwb2r0jPL7HzB5EOW/nwr4JYZxSF/bqhqvduGkbQZhbgXmsMwWEC4Q==
    REDIS_PASSWORD: AgBM+QCMiR+F7YwoBMhSzjHptgRd/e5oumoSpJi1tOrbzSn+naO3V4pygKGHKDSlUb1Qt1DJZ4GppvvVCuwTgfX0ZNQWWN8222Zx0jzwTYYMBzzD++ER5vMiO6krd/StRFVk4qDLTMMOGJy1rk3EwcA3gyCOS/azr/CLI2UVe4bL5hmyLEKkETXkcN0sHy9vj/atd0CIasRCTv2bCNTX9eHTw54IQ8x0DLg0B9gtKTwAyWMIzDNL2BbAVLZqCjxF/uyOVZcQQD6uuay+xjnJ58n3Xm5OUjbCzNbuWKYcitQvBd/fhum/Tmmnie8jOK+zL1t/W4s/UJ4XxhQUKJzJPztyQth+/H6hdbJiNjdnQ53bTqUHOhMsqNvmHYQYNEQml+m4knCoonS5kzhUB9A2kGxhQ4sM1qCAum+iM/gXTP4SYRHMk82jCfnuoSZvdfQXJBcNkb6ZWtXBzE9rG4yZQ+DGnFVvMuLzuhj/fIn7VJomwDRoJq3NfSXfraAmeIwKBMyTaXLJkGI20mdgRV/5jusWuBDo5ITtwk6H1bqPjqQZ7XR9L3rHlpXYs4/uIgDM6+OLaAhD6QATvNsmbzY6djW2kkDgAvkp8jjLb+S99XZNyLa7wJw6Th8DWbFN2MlYa6TxTbZsnJwlfe/evRZrGBSWynoUZ0Hp08u/bNfwooFUY41uorm8Q9gwTKY2Bifkjx5RNxcTuA==
  template:
    metadata:
      creationTimestamp: null
      name: worker-secret
      namespace: default
    type: Opaque
