---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: worker-secret
  namespace: default
spec:
  encryptedData:
    AMQP_URL: AgCOCj7NYw90oMhLSDjP/857Ikcy/P3GylFZMCSMA9aAyodSMwUDVYEyWVqvgX/kUxic97s+pzdls494u+c1lxAE1dR3yjsewhP8rtwun1GTps1HsJpR8VusNx37NTCK1PRCqf0G/iYYc7h58+3/ZRVSSh9EU0pIgAFho0sZ6xBVmmDlfabimGH522OPUgnv8WTgCu9BlztfW83diOmTWXYYgRihWvjR82JEpewAsy8RdiAhHwXIYH4tuFjVnKXKESiIQ3NhT43i0c1PQO0peQPugK1iNSOQzEcREPEcah4St67Y9N9odpFSF0/j/sYfbF7Z4Nkjc7sIx5XkHRiUHPwGzUYZoJ7+J3In6myWGILDGm2ZwtKMJPcp6ZLsKa3ZnOHgrHOi/EqbJNy0RzvfPcEHkOAceao1BpA0Dy2ae0SdKULxglpVGi3XApwNKRurI1S6DenrqSX0Z4XE0wo5YDiL6GTeUuE2x2CDUJIrPfgjC6pKw7O6l15Mh7y0FQ5RpiVY7cj3ui2jm/Mb7FrkhT0PiPvuSD7tuCMHKx1lh3HwrA2L9fxinFHjAcDkjtJ7fdPce2GCZ+LNXtbIWtby0z8dYuczc6Iky+HfvyKm46r3gQnKjRa3R+BGuLaBJU7vBZ79DYnBKqU1GW5MAkbCX0f9tsMQHWZ797bUuz4TvyC1HsUHHeyAwK7Rcv0MzEz7fJFruZV9YL/T7fskHhIEDfttW8QEG9LlpNi4vdYow+2P8g==
    REDIS_PASSWORD: AgBGJjQwjYDhhQxg2OCHOAHKYSUR5UMqhJtzwHynvKqpY6vUOAyyk9w0YGgo96EFed5xfOR3Gj2/pctvoPkjlcqFvj9Zavrz+CBEL8XGSMvAL1sRHmYT6hpa+l6aRcwVrAmnr5h077NA/nRBn3Xv8vUCrz4+NAi1hI8f32on005OsiO6iLjiuBp5/FHcQFu5Mq5GVVLBTF2K1mYBpj+UUSFVFmybFrrLGxMWaly+Rwra01iE4rze02+MGQ5CJqDTWQSeZRtpESREaQtDEUZ1yXklIowslzTV8WzTBa+59643sjxYXIc1OcNsOF1cCQgjVVdXeQ9AMwGC2Ml5SsmVvsmliGpvmD61jmSvtyWJpPfn0pA6fvKfsnmbKydUDZchOxriu31cChb2oeD3FUiVxCUu7NPZnantq0ux8rhzvFMDQDZ9exP18HqHC1rYWm9GInp2jIC1T2ZUOXDgmj3xUhfzVsBUBmxiBR1G2tfZrYhh08AXlTVg2lN2f5iPlQ2BAeKIXbvTjoIAs6L42gB42TDTTb4AuWuU5Y6HJxPTR9hRYWYx9Sfj1HUbf7S9qb3uNnPUHkPHkCzUgtBYiuYVWAUR7C/HQfWNsGjtrZQLdDhKtabPv0qFB9ir9P6I2c4fjwyMl/8SKKGhcjsTg9fV2zxwtyxDGYVOfxtH/rJDH0r/J/9vzvaIZdmJYPzulZB1+LGdz3RxRg==
  template:
    metadata:
      creationTimestamp: null
      name: worker-secret
      namespace: default
    type: Opaque
